#+Title:  Accurate summation of some number theoretic series
#+Author: Victor S. Miller
#+latex_header: \usepackage{amsthm}
#+latex_header: \newtheorem{definition}{Definition}
#+latex_header: \newtheorem{proposition}{Proposition}
#+Options: toc:nil

* Introduction
On the ~math-fun~ mailing list, Neil Sloane posed the following
problem:

Let $V(n)$ denote the function which takes a positive integer, $n$ and
uses its base 10 digits in a base 11 representation. Evaluate the
series
$$S_1 := \sum_{n=1}^\infty \frac{1}{V(n)}$$
and
$$S_2 := \sum_{p, \text{prime}} \frac{1}{V(p)}.$$
We now that both series converge since they are subseries of one
considered by Kempner (or its generalization).
The first series can be accurately evaluated using a method of Baillie
which uses the recursive structure of the set $\{V(n)\}$. However, the
second series has no such easily seen recursive structure. We first
describe the method of Baillie, and then give an approach to
estimating the value of the second series.

In 1914, Kempner considered the summation of subseries of the harmonic
series:

$$\sum_{n=1}^\infty \frac{1}{n}.$$

It's well known that this series diverges. More specifically

$$\sum_{n=1}^N \frac{1}{n} \sim \log N.$$

However, Kempner noted that
one restricted the summands to those integers whose base 10
representation omitted one digit, then the series would converge.
Later Irwin considered what would happen in one had further
restrictions on the digits. For example, suppose that at most 2 of the
digit 1 were allowed.  In all such cases the series would converge. A
simple way to see this (as noted in Hardy and Wright), is to write
$s(i)$ to denote the sum of $\frac{1}{n}$ where $n$ has exactly $i$
digits, and its base 10 reprensentation omits the digit $d$. One notes
that there are at most $9^i$ terms, and each term is
$\le \frac{1}{10^{i-1}}$.  Thus the sum in question is

$$\le 9 \sum_{i=1}^\infty \left( \frac{9}{10}\right)^{i-1} = 90.$$

* Baillie's method
In "Sums of Reciprocals of Integers Missing a Given Digit", Baillie
gives a method of greatly accelerating the convergence of such series
to their true value. He notes that straightforward summation converges
extremely slowly. An argument similar to the above [fn:1] shows that

$$\sum_{i=k}^\infty s(i) \ge \sum_{i=k}^\infty \frac{9^i}{10^i} = 10 (9/10)^k.$$

Baillie's method makes use of the recursive nature of
the set of allowed integers. More specifically, suppose that we are
interested in the base $b$ reprentation of integers which omit the
digit $d$. Baillie generalizes the above. Let $C$ denote the set of
allowed integers (i.e. those whose base $b$ reprensentation omits the
digit $d$), and let $C_i$ denote the set of those member of $C$ which
have exactly $i$ digits, and $D$ the set of allowed digits.
Then define
$s(i,j) = \sum_{n \in C_i} \frac{1}{n^j}$. The original sum is then
$\sum_{i=1}^\infty s(i,1)$. Baillie notes that $C_1 = D \backslash
\{0\}$ and, for $i > 1$, we have

$$C_i = \{b x + j: x \in C_{i-1}, j=0,\dots, b-1, j \ne d\}.$$

Thus, for $i > 1, j \ge 1$ we have
$$s(i,j) = \sum_{x \in C_i, k \in D} \left(\frac{1}{bx+k}\right)^j.$$

Using the binomial theorem we have

$$(bx+k)^{-j} = (bx)^j\sum_{n=0}^\infty \binom{-j}{n} \left( \frac{k}{bx}\right)^n.$$

Since this series is absolutely convergent (the  absolute values of
its terms are
dominated by the terms of the series $(bx^j)(1-k/(bx))^j$), we have
$$s(i,j) = \sum_{n=0}^\infty a(j,n) s(i-1,j+n),$$
where
$c_n = \sum_{k \in D} k^n$ and $a(j,n) = c_n \binom{-j}{n}/b^{j+n}$
It is useful to note that $\binom{-j}{n} = (-1)^n
\binom{j+n-1}{n}$.
* Bounding the tail of the infinite series
For proper accuracy one needs an estimate of the
tail of this series
$$R(i,j,k) = \sum_{n=k}^\infty a(j,n) s(i,j+n).$$

From the above we have

$$|s(i,j+n)| \le \frac{(b-1)^i}{b^{(i-1)(j+n)}} = b^{j+n}\left(\frac{b-1}{b^{j+n}} \right)^i$$

and

$$|a(j,n)| \le \frac{b^n}{n} \binom{j+n-1}{n} / b^{n+j}.$$
Thus

$$|R(i,j,k)| \le (b-1)^i b^{-ij} \sum_{n=k}^\infty \binom{j+n-1}{n} b^{-in}.$$

We use the ideas in "Series Acceleration via Negative Binomial
Probabilities" by Jose Adell. He first define a random variable
$X_j(t)$, for $j>0$ and integer, and $t>0$, which is a negative binomial variable:

$$\Pr(X_j(t) = k) =  \binom{j+k-1}{k} \left( \frac{t}{t+1} \right)^k (t+1)^{-j} 
= (t+1)^{-j}\binom{-j}{k} \left(\frac{-t}{t+1}\right)^k.$$

We see that the above upper bound for $|R(i,j,k)|$ is exactly
$(b-1)^i/(b^i-1)^j \Pr(X_j(1/(b^i-1)) \ge k)$.

He then proves that
$$\Pr(X_j(t) \ge k) \le C_j(t,k) \left(\frac{t}{t+1}\right)^k,$$
where $$C_j(t,k) = \left(\frac{k e^{1+j/(2k)}}{j(t+1)} \right)^j.$$

He then considers, for $\theta> 1$ the random variable
$\theta^{X_j(t)}$. It is straightforward to calculate
$$E(\theta^{X_j(t)}) = (t+1)^{-j}\sum_{k=0}^\infty \binom{-j}{k}\theta^k
(-t/(t+1))^k = (1 + t(1- \theta))^{-j}. $$
The last sum in question is the tail of $(1-b^{-(i-1)})^{-j}$. To get
a good, but crude, estimate of this consider the ration between
successive terms of $\binom{j+n-1}{n} x^n$:
$(1/x) \binom{j+n-1}{n}/\binom{j+n}{n+1} = \frac{n+1}{(j+n)x}$. We
have $(n+1)/((j+n)x) \le \alpha$ if and only if
$n(1-\alpha x) \le \alpha j x - 1$. This suggests taking
$\alpha = 1/x$. Thus

$$|R(i,j,k)| \le \binom{k+n-1}{n} b^{-(i-1)k}(b-1)^k b^{-ij} = \binom{j+k-1}{k} ((b-1)/b^{j+k-1})^i.$$

[fn:1] If $0 \in D$ this needs to be slightly modified since $|C_i| = (b-2)(b-1)^{i-1}$.

* An alternate bound

For an alternate bound we first prove the following:

\begin{definition}
if $n$ and $a$ are positive integers, we say that $n$ \emph{starts with} $a$ if $n = a \cdot 10^b + c$ for some nonnegative integers $b,c$ with $c < 10^b$.
\end{definition}
\begin{proposition}
Let $n$ and $a$ be positive integers.
If $n$ starts with $a$ then
\begin{displaymath}
\frac{V(a)}{(a+1)^\alpha} \le \frac{V(n)}{n^\alpha} < \frac{V(a) + \frac{9}{10}}{a^\alpha},
\end{displaymath}
where $\alpha = \frac{\log 11}{\log 10}$.
\end{proposition}
\begin{proof}
If $n$ starts with $a$, then
$a = a \cdot 10^b + c$ with $c < 10^b$. Thus
$$a \cdot 10^b \le n < (a+1) \cdot 10^b.$$ Rearranging, and taking logarithms yields
\begin{displaymath}
\frac{\log n - \log (a+1)}{\log 10}  < b \le \frac{\log n - \log a}{\log 10}.
\end{displaymath}
However, we have $V(n) = V(a) 11^b + V(c)$, and $V(c) \le \sum_{i=0}^{b-1} 9 \cdot 11^i = (9/10) (11^b - 1)$.
Plugging in the bounds for $b$ we get the indicated result
\end{proof}

We first make a simple use of this proposition.
\begin{proposition}
Let $m > 1$ be a positive integer. If $s \in \CC, \Re s > 1$, define the \emph{prime zeta function} $P(s) = \sum_{p \text{ prime}} \frac{1}{p^s}$.
Let $$I_m(s) = \sum_{p \le 10^m \text{ prime}} \frac{1}{p^s}$$
$$L_m(s) = \sum_{p > 10^m, \text{ prime}} \frac{1}{p^s} = P(s) - I_m(s),$$
$$\ell_m = 1 / \max_{10^{m-1} \le a < 10^m} (a^\alpha/(V(a)  + 0.9))$$
$$u_m = 1 / \min_{10^{m-1} \le a < 10^m} ((a+1)^\alpha/(V(a))).$$

 We then have

$$\ell_m (P(\alpha) - I_m(\alpha)) \le S_2 -  \sum_{p \le 10^m \text{ prime}} \frac{1}{V(p)} \le u_m (P(\alpha) - I_m(\alpha)),$$

where $\alpha = \log 11 / \log 10$.
\end{proposition}
